//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARISClient.ARISWSTestFramework {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/ceremp/common")]
    public partial class ArisFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string dField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
                this.RaisePropertyChanged("D");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class UploadDataResponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseIdField;
        
        private string fileNameField;
        
        private string loadCodeField;
        
        private string validationKeyField;
        
        private bool validField;
        
        private string validationErrorCodeField;
        
        private string validationErrorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string loadCode {
            get {
                return this.loadCodeField;
            }
            set {
                this.loadCodeField = value;
                this.RaisePropertyChanged("loadCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string validationKey {
            get {
                return this.validationKeyField;
            }
            set {
                this.validationKeyField = value;
                this.RaisePropertyChanged("validationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string validationErrorCode {
            get {
                return this.validationErrorCodeField;
            }
            set {
                this.validationErrorCodeField = value;
                this.RaisePropertyChanged("validationErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string validationErrorDescription {
            get {
                return this.validationErrorDescriptionField;
            }
            set {
                this.validationErrorDescriptionField = value;
                this.RaisePropertyChanged("validationErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/ceremp/common")]
    public partial class HeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime qualifiedDateTimeField;
        
        private bool qualifiedDateTimeFieldSpecified;
        
        private string reportingEntityField;
        
        private string identityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime qualifiedDateTime {
            get {
                return this.qualifiedDateTimeField;
            }
            set {
                this.qualifiedDateTimeField = value;
                this.RaisePropertyChanged("qualifiedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qualifiedDateTimeSpecified {
            get {
                return this.qualifiedDateTimeFieldSpecified;
            }
            set {
                this.qualifiedDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("qualifiedDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReportingEntity {
            get {
                return this.reportingEntityField;
            }
            set {
                this.reportingEntityField = value;
                this.RaisePropertyChanged("ReportingEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
                this.RaisePropertyChanged("Identity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class UploadDataRequestMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderType headerField;
        
        private string fileNameField;
        
        private string validationKeyField;
        
        private byte[] uploadedDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public HeaderType header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string validationKey {
            get {
                return this.validationKeyField;
            }
            set {
                this.validationKeyField = value;
                this.RaisePropertyChanged("validationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] uploadedData {
            get {
                return this.uploadedDataField;
            }
            set {
                this.uploadedDataField = value;
                this.RaisePropertyChanged("uploadedData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="aris-services", Namespace="http://www.acer.europa.eu/aris", ConfigurationName="ARISWSTestFramework.arisservices")]
    public interface arisservices {
        
        // CODEGEN: Generating message contract since the operation UploadData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acer.europa.eu/aris/UploadData", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARISClient.ARISWSTestFramework.ArisFault), Action="http://www.acer.europa.eu/aris/UploadData", Name="fault", Namespace="http://www.acer.europa.eu/ceremp/common")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ARISClient.ARISWSTestFramework.UploadDataResponse UploadData(ARISClient.ARISWSTestFramework.UploadDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acer.europa.eu/aris/UploadData", ReplyAction="*")]
        System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.UploadDataResponse> UploadDataAsync(ARISClient.ARISWSTestFramework.UploadDataRequest request);
        
        // CODEGEN: Generating message contract since the operation ElaborationStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acer.europa.eu/aris/ElaborationStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARISClient.ARISWSTestFramework.ArisFault), Action="http://www.acer.europa.eu/aris/ElaborationStatus", Name="fault", Namespace="http://www.acer.europa.eu/ceremp/common")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ARISClient.ARISWSTestFramework.ElaborationStatusResponse ElaborationStatus(ARISClient.ARISWSTestFramework.ElaborationStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acer.europa.eu/aris/ElaborationStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.ElaborationStatusResponse> ElaborationStatusAsync(ARISClient.ARISWSTestFramework.ElaborationStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation NameConventionCheck is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acer.europa.eu/aris/NameConventionCheck", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ARISClient.ARISWSTestFramework.ArisFault), Action="http://www.acer.europa.eu/aris/NameConventionCheck", Name="fault", Namespace="http://www.acer.europa.eu/ceremp/common")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ARISClient.ARISWSTestFramework.NameConventionCheckResponse NameConventionCheck(ARISClient.ARISWSTestFramework.NameConventionCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acer.europa.eu/aris/NameConventionCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.NameConventionCheckResponse> NameConventionCheckAsync(ARISClient.ARISWSTestFramework.NameConventionCheckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDataRequest", Namespace="http://www.acer.europa.eu/aris/upload", Order=0)]
        public ARISClient.ARISWSTestFramework.UploadDataRequestMessage UploadDataRequest1;
        
        public UploadDataRequest() {
        }
        
        public UploadDataRequest(ARISClient.ARISWSTestFramework.UploadDataRequestMessage UploadDataRequest1) {
            this.UploadDataRequest1 = UploadDataRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDataResponse", Namespace="http://www.acer.europa.eu/aris/upload", Order=0)]
        public ARISClient.ARISWSTestFramework.UploadDataResponseMessage UploadDataResponse1;
        
        public UploadDataResponse() {
        }
        
        public UploadDataResponse(ARISClient.ARISWSTestFramework.UploadDataResponseMessage UploadDataResponse1) {
            this.UploadDataResponse1 = UploadDataResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class ElaborationStatusRequestMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderType headerField;
        
        private string loadCodeField;
        
        private ElaborationStatusRequestMessageReceiptType receiptTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public HeaderType header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string loadCode {
            get {
                return this.loadCodeField;
            }
            set {
                this.loadCodeField = value;
                this.RaisePropertyChanged("loadCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ElaborationStatusRequestMessageReceiptType receiptType {
            get {
                return this.receiptTypeField;
            }
            set {
                this.receiptTypeField = value;
                this.RaisePropertyChanged("receiptType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.acer.europa.eu/aris/upload")]
    public enum ElaborationStatusRequestMessageReceiptType {
        
        /// <remarks/>
        RRM_RESTRICTED,
        
        /// <remarks/>
        MP_RESTRICTED,
        
        /// <remarks/>
        GLOBAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class ElaborationStatusResponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseIdField;
        
        private string loadCodeField;
        
        private ElaborationStatusResponseMessageResult resultField;
        
        private byte[] receiptFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string loadCode {
            get {
                return this.loadCodeField;
            }
            set {
                this.loadCodeField = value;
                this.RaisePropertyChanged("loadCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ElaborationStatusResponseMessageResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] receiptFile {
            get {
                return this.receiptFileField;
            }
            set {
                this.receiptFileField = value;
                this.RaisePropertyChanged("receiptFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.acer.europa.eu/aris/upload")]
    public enum ElaborationStatusResponseMessageResult {
        
        /// <remarks/>
        COMPLETE,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        ONGOING,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ElaborationStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ElaborationStatusRequest", Namespace="http://www.acer.europa.eu/aris/upload", Order=0)]
        public ARISClient.ARISWSTestFramework.ElaborationStatusRequestMessage ElaborationStatusRequest1;
        
        public ElaborationStatusRequest() {
        }
        
        public ElaborationStatusRequest(ARISClient.ARISWSTestFramework.ElaborationStatusRequestMessage ElaborationStatusRequest1) {
            this.ElaborationStatusRequest1 = ElaborationStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ElaborationStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ElaborationStatusResponse", Namespace="http://www.acer.europa.eu/aris/upload", Order=0)]
        public ARISClient.ARISWSTestFramework.ElaborationStatusResponseMessage ElaborationStatusResponse1;
        
        public ElaborationStatusResponse() {
        }
        
        public ElaborationStatusResponse(ARISClient.ARISWSTestFramework.ElaborationStatusResponseMessage ElaborationStatusResponse1) {
            this.ElaborationStatusResponse1 = ElaborationStatusResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class NameConventionCheckRequestMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderType headerField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public HeaderType header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class NameConventionCheckResponseMessage : CheckResponseMessage {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameConventionCheckResponseMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acer.europa.eu/aris/upload")]
    public partial class CheckResponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseIdField;
        
        private string fileNameField;
        
        private string validationKeyField;
        
        private bool validField;
        
        private string validationErrorCodeField;
        
        private string validationErrorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseId {
            get {
                return this.responseIdField;
            }
            set {
                this.responseIdField = value;
                this.RaisePropertyChanged("responseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string validationKey {
            get {
                return this.validationKeyField;
            }
            set {
                this.validationKeyField = value;
                this.RaisePropertyChanged("validationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string validationErrorCode {
            get {
                return this.validationErrorCodeField;
            }
            set {
                this.validationErrorCodeField = value;
                this.RaisePropertyChanged("validationErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string validationErrorDescription {
            get {
                return this.validationErrorDescriptionField;
            }
            set {
                this.validationErrorDescriptionField = value;
                this.RaisePropertyChanged("validationErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameConventionCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameConventionCheckRequest", Namespace="http://www.acer.europa.eu/aris/upload", Order=0)]
        public ARISClient.ARISWSTestFramework.NameConventionCheckRequestMessage NameConventionCheckRequest1;
        
        public NameConventionCheckRequest() {
        }
        
        public NameConventionCheckRequest(ARISClient.ARISWSTestFramework.NameConventionCheckRequestMessage NameConventionCheckRequest1) {
            this.NameConventionCheckRequest1 = NameConventionCheckRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameConventionCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameConventionCheckResponse", Namespace="http://www.acer.europa.eu/aris/upload", Order=0)]
        public ARISClient.ARISWSTestFramework.NameConventionCheckResponseMessage NameConventionCheckResponse1;
        
        public NameConventionCheckResponse() {
        }
        
        public NameConventionCheckResponse(ARISClient.ARISWSTestFramework.NameConventionCheckResponseMessage NameConventionCheckResponse1) {
            this.NameConventionCheckResponse1 = NameConventionCheckResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface arisservicesChannel : ARISClient.ARISWSTestFramework.arisservices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class arisservicesClient : System.ServiceModel.ClientBase<ARISClient.ARISWSTestFramework.arisservices>, ARISClient.ARISWSTestFramework.arisservices {
        
        public arisservicesClient() {
        }
        
        public arisservicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public arisservicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public arisservicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public arisservicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARISClient.ARISWSTestFramework.UploadDataResponse ARISClient.ARISWSTestFramework.arisservices.UploadData(ARISClient.ARISWSTestFramework.UploadDataRequest request) {
            return base.Channel.UploadData(request);
        }
        
        public ARISClient.ARISWSTestFramework.UploadDataResponseMessage UploadData(ARISClient.ARISWSTestFramework.UploadDataRequestMessage UploadDataRequest1) {
            ARISClient.ARISWSTestFramework.UploadDataRequest inValue = new ARISClient.ARISWSTestFramework.UploadDataRequest();
            inValue.UploadDataRequest1 = UploadDataRequest1;
            ARISClient.ARISWSTestFramework.UploadDataResponse retVal = ((ARISClient.ARISWSTestFramework.arisservices)(this)).UploadData(inValue);
            return retVal.UploadDataResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.UploadDataResponse> ARISClient.ARISWSTestFramework.arisservices.UploadDataAsync(ARISClient.ARISWSTestFramework.UploadDataRequest request) {
            return base.Channel.UploadDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.UploadDataResponse> UploadDataAsync(ARISClient.ARISWSTestFramework.UploadDataRequestMessage UploadDataRequest1) {
            ARISClient.ARISWSTestFramework.UploadDataRequest inValue = new ARISClient.ARISWSTestFramework.UploadDataRequest();
            inValue.UploadDataRequest1 = UploadDataRequest1;
            return ((ARISClient.ARISWSTestFramework.arisservices)(this)).UploadDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARISClient.ARISWSTestFramework.ElaborationStatusResponse ARISClient.ARISWSTestFramework.arisservices.ElaborationStatus(ARISClient.ARISWSTestFramework.ElaborationStatusRequest request) {
            return base.Channel.ElaborationStatus(request);
        }
        
        public ARISClient.ARISWSTestFramework.ElaborationStatusResponseMessage ElaborationStatus(ARISClient.ARISWSTestFramework.ElaborationStatusRequestMessage ElaborationStatusRequest1) {
            ARISClient.ARISWSTestFramework.ElaborationStatusRequest inValue = new ARISClient.ARISWSTestFramework.ElaborationStatusRequest();
            inValue.ElaborationStatusRequest1 = ElaborationStatusRequest1;
            ARISClient.ARISWSTestFramework.ElaborationStatusResponse retVal = ((ARISClient.ARISWSTestFramework.arisservices)(this)).ElaborationStatus(inValue);
            return retVal.ElaborationStatusResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.ElaborationStatusResponse> ARISClient.ARISWSTestFramework.arisservices.ElaborationStatusAsync(ARISClient.ARISWSTestFramework.ElaborationStatusRequest request) {
            return base.Channel.ElaborationStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.ElaborationStatusResponse> ElaborationStatusAsync(ARISClient.ARISWSTestFramework.ElaborationStatusRequestMessage ElaborationStatusRequest1) {
            ARISClient.ARISWSTestFramework.ElaborationStatusRequest inValue = new ARISClient.ARISWSTestFramework.ElaborationStatusRequest();
            inValue.ElaborationStatusRequest1 = ElaborationStatusRequest1;
            return ((ARISClient.ARISWSTestFramework.arisservices)(this)).ElaborationStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ARISClient.ARISWSTestFramework.NameConventionCheckResponse ARISClient.ARISWSTestFramework.arisservices.NameConventionCheck(ARISClient.ARISWSTestFramework.NameConventionCheckRequest request) {
            return base.Channel.NameConventionCheck(request);
        }
        
        public ARISClient.ARISWSTestFramework.NameConventionCheckResponseMessage NameConventionCheck(ARISClient.ARISWSTestFramework.NameConventionCheckRequestMessage NameConventionCheckRequest1) {
            ARISClient.ARISWSTestFramework.NameConventionCheckRequest inValue = new ARISClient.ARISWSTestFramework.NameConventionCheckRequest();
            inValue.NameConventionCheckRequest1 = NameConventionCheckRequest1;
            ARISClient.ARISWSTestFramework.NameConventionCheckResponse retVal = ((ARISClient.ARISWSTestFramework.arisservices)(this)).NameConventionCheck(inValue);
            return retVal.NameConventionCheckResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.NameConventionCheckResponse> ARISClient.ARISWSTestFramework.arisservices.NameConventionCheckAsync(ARISClient.ARISWSTestFramework.NameConventionCheckRequest request) {
            return base.Channel.NameConventionCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<ARISClient.ARISWSTestFramework.NameConventionCheckResponse> NameConventionCheckAsync(ARISClient.ARISWSTestFramework.NameConventionCheckRequestMessage NameConventionCheckRequest1) {
            ARISClient.ARISWSTestFramework.NameConventionCheckRequest inValue = new ARISClient.ARISWSTestFramework.NameConventionCheckRequest();
            inValue.NameConventionCheckRequest1 = NameConventionCheckRequest1;
            return ((ARISClient.ARISWSTestFramework.arisservices)(this)).NameConventionCheckAsync(inValue);
        }
    }
}
